namespace Common.Enums
{
    public enum MessageCode
    {
        Success = 1,
        Error = 2,
        Login = 3,
        Logout = 4,
        Register = 5,
        ChangePassword = 6,
        UpdateProfile = 7,
        ForgetPassword = 8,
        GameGuide = 9,
        GetListFriend = 10,
        GetRooms = 11,
        DeleteFriendship = 12,
        GetGame = 14,
        GetRank = 16,
        AddFeedback = 18,
        ManageUser = 20,
        CreateRoom = 13,
        Disconnected = 36,
        RefreshRooms = 15,
        JoinRoom = 17,
        RefreshCurrentRoom = 19,
        ChangeStatus = 22,
        GetAllUser = 24,
        AddNotification = 26,
        GetFeedback = 28,
        CheckFeedback = 30,
        Maintain = 32,
        ForceLogout = 34,
        AddFriend = 38,
        ReplyAddFriend = 40,
        InvitePlay = 42,
        ReplyInvitePlay = 44,
        CaroMove = 43,
        InvalidMove = 41,
        ChangeReadyState = 45,
        OutRoom = 47,
        Notification = 46,
        GameStarted = 48,
        GameEnded = 50
    }
}
